### PR TITLE
Fix libgcrypt init, _free_photo, and the duplicate ID thing

### PR DESCRIPTION
**Pull request by BenWiederhake**
Otherwise, this spews an ugly warning, e.g. in Finch:
`Libgcrypt warning: missing initialization - please fix the application`

Sorry that I didn't implement proper initialization from the start, I thought I could get away without it :P

### CODE REVIEW

**Comment by majn** [comment]
You are fast 👍

**Comment by BenWiederhake** [comment]
Only when I'm actually working on something :P
Don't forget that I didn't move a finger during the last 4-5 weeks.

**Comment by BenWiederhake** [comment]
Sorry for the wrong push.
Added the fix to #85, which doesn't show up in github issues. (That bug is known in tgp as https://github.com/majn/telegram-purple/issues/220#issuecomment-172539194 )

**Comment by BenWiederhake** [comment]
@vysheng: Is there anything preventing this from being pushed? Can I help somehow?

**Comment by BenWiederhake** [comment]
@vysheng: Is there anything preventing this from being pushed? Can I help somehow?

Please merge this, it fixes two crashing bugs and a security warning thing.

**Comment by BenWiederhake** [comment]
@vysheng: Is there anything preventing this from being pushed? Can I help somehow?

Please merge this, it fixes two crashing bugs and a security thing.

**Comment by BenWiederhake** [comment]
Pushed two more commits that fix user-visible bugs.

@vysheng: Is there anything preventing this from being pushed? Can I help somehow?  Does this need rebasing?

Please merge this, by now it fixes at least four crashing bugs and a security thing.

**Comment by BenWiederhake** [comment]
Fixed the OpenSSL-version of the `TGLC_init` function, introduced in the first of the commits.

@vysheng: Is there anything preventing this from being pushed? Can I help somehow?  Does this need rebasing?

Please merge this, by now it fixes at least four crashing bugs and a security thing.

**Comment by BenWiederhake** [comment]
Swallowed by #97

**Pull request closed without merging**
